queue_rules:
  - name: default
    # Conditions a PR must meet to ENTER the queue
    queue_conditions:
      - check-success=test
      - label=ready-to-merge
      - -draft
    # Conditions that must hold to actually merge out of the queue
    merge_conditions:
      - check-success=test
    # Batch up to 2 PRs together before merging
    batch_size: 2
    batch_max_wait_time: 10 min
