queue_rules:
  - name: default
    queue_conditions:
      - check-success=test
      - label=ready-to-merge
      - -draft
    merge_conditions:
      - check-success=test
    batch_size: 2
    batch_max_wait_time: 10 min
pull_request_rules:
  - name: Ping PR author when conflicting
    description: Warn the pull request author when their PR are conflicting
    conditions:
      - conflict
      - -closed
    actions:
      comment:
        message: >
          👋 {{author}} your PR is conflicting and needs to be updated to be
          merged
  - name: Add to merge queue when ready
    conditions:
      - label=ready-to-merge
      - check-success=test
      - -draft
    actions:
      queue:
        name: default
  - name: Request review from code owner
    conditions:
      - -draft
      - "#approved-reviews-by=0"
      - -label=WIP
    actions:
      request_reviews:
        users:
          - cipick
  - name: Add WIP label when title starts with WIP
    conditions:
      - title~=^WIP
    actions:
      label:
        add:
          - WIP
  - name: Remove WIP label when title no longer starts with WIP
    conditions:
      - title!~=^WIP
      - label=WIP
    actions:
      label:
        remove:
          - WIP
  - name: Label small PRs (fewer than 10 files changed)
    conditions:
      - files<10
    actions:
      label:
        add:
          - size/small
  - name: Label large PRs (more than 50 files changed)
    conditions:
      - files>50
    actions:
      label:
        add:
          - size/large
  - name: Label bug-fix branches
    conditions:
      - head~=^fix/
    actions:
      label:
        add:
          - bug
  - name: Label feature branches
    conditions:
      - head~=^feat/
    actions:
      label:
        add:
          - feature
